---
  openapi: "3.0.0"
  info:
    title: "EHRI Search API"
    description: "Search the EHRI portal"
  consumes:
    - application/json
  produces:
    - application/vnd.api+json
  servers:
    - url: http://localhost:9000/api
